### PR TITLE
Julia 568

### LINKED ISSUE #568: Number game pieces resetting
If you hit the back button on the match page the number of game pieces always resets back to 8.

### LINKED ISSUE #570: App Crash
If you enter a number much to large into the number of game pieces the app crashes when it tries to convert that string into an int much larger than the integer bit limit. 

The app also does not stop you from entering any other number as the number of game pieces, it should cap it at 8.

### LINKED ISSUE #571: Logger should output D and E records with consistent first few fields
Right now, D record looks like:
`D,5,1,q,false,9613,,3663,P,...
`
and E record looks like:
`E,5,1,9613,q,1,
`

They should BOTH be consistent (to make it easier to read and process).  I suggest:

<RecordType>,<CompId>,<MatchType>,<MatchNumber>,<Team>, and then the rest per record type.  So:

`D,5,q,1,9613,false,...
`
`E,5,q,1,9613,1,...`

### PR DESCRIPTION
**Pull request by juliakim-stu**
fixes #568
fixes #570 
fixes #571 

fixes number of game pieces resetting when back button is pressed
caps the number of game pieces at 8, and the match number at three digits

reorders logger so both are consistent

### CODE REVIEW

File: app/src/main/java/com/team3663/scouting_app/activities/PreMatch.java [hunk 1]
```diff
@@ -227,11 +239,34 @@ private void initDidPlay() {
...
+            editNumStartingGamePiece.setText(String.valueOf(Globals.numStartingGamePiece));
+        }
 
-        // Create text box to input robot's starting number of game pieces
-        preMatchBinding.editNumStartingGamePiece.setText(String.valueOf(Globals.numStartingGamePiece));
+        // when user inputs a number of starting game pieces, update the global to log the correct value
+        editNumStartingGamePiece.addTextChangedListener(new TextWatcher() {
+            @Override
+            public void beforeTextChanged(CharSequence num, int start, int count, int after) {}
+            @Override
```
Comment (Jeff-Stammler) [inline app/src/main/java/com/team3663/scouting_app/activities/PreMatch.java]: add a comment that this is called WHILE text is being typed (ie: every keystroke)

**Review by Jeff-Stammler — CHANGES_REQUESTED** [review]
looks good, just small fixes.
