### PR TITLE
Team Number / Override fixes

### LINKED ISSUE #245: When you add a team using the override button, it should only be added for that match.
Currently, the override button adds the team to the spinner for the entire time you are using the app.

### PR DESCRIPTION
**Pull request by Jeff-Stammler**
fixes #245 

handles blanking out the match,
changing the match (if we have match data)
changing the match (if we don't have match data)

handles override team (if we have match data)
handles override team (if we don't have match data)

Handle adding override team number back into spinner if you hit the "back" button from Match.

use the DROPDOWN_NO_ITEMS global for when there's no teams

### CODE REVIEW

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java [hunk 1]
```diff
@@ -552,7 +555,7 @@ public void run() {
     }
 
     // =============================================================================================
-    // Function:    end_match
+    // Function:    end_Teleop
```
Comment (AdrielStammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:558]: Oops

**Review by AdrielStammler — APPROVED** [review]
