### PR TITLE
Start Position Fix

### LINKED ISSUE #151: Pre-Match: default StartingPos if "Did They Play" is false
Currently, we default "did they play" to true, but the default starting positions is "did not play". this doesn't make sense.

We can have a "Choose one..." perhaps as the default?  Also need to add this into the check that all fields were supplied.  This should be considered "not filled in" if chosen.

Also, if "did they play?" is unchecked, we should default the starting position to "did not play" as well.
And if unchecked, default back to "choose one...".

### PR DESCRIPTION
**Pull request by AdrielStammler**
It is now required to continue and will cause a toast message, did not play isn't an option, will be overridden with did not play if that is the case, and is by default "Choose one".

Fixes #151

### CODE REVIEW

File: app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java [hunk 1]
```diff
@@ -184,7 +184,9 @@ public void onClick(View view) {
                         Globals.EventLogger.LogData(Constants.LOGKEY_SCOUTER, preMatchBinding.editScouterName.getText().toString().toUpperCase());
                         Globals.EventLogger.LogData(Constants.LOGKEY_DID_PLAY, String.valueOf(preMatchBinding.checkboxDidPlay.isChecked()));
                         Globals.EventLogger.LogData(Constants.LOGKEY_TEAM_SCOUTING, String.valueOf(Globals.CurrentScoutingTeam));
-                        Globals.EventLogger.LogData(Constants.LOGKEY_START_POSITION, String.valueOf(Globals.StartPositionList.getStartPositionId(preMatchBinding.spinnerStartingPosition.getSelectedItem().toString())));
+                        if (checkbox_DidPlay.isChecked())
+                            Globals.EventLogger.LogData(Constants.LOGKEY_START_POSITION, String.valueOf(Globals.StartPositionList.getStartPositionId(spinner_StartPos.getSelectedItem().toString())));
+                        else Globals.EventLogger.LogData(Constants.LOGKEY_START_POSITION, "Did Not Play");
```
Comment (Jeff-Stammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/PreMatch.java:189]: Let's not hard code "Did Not Play".  we'll know in Tableau they didn't play.  You really don't need to log anything.  The Logger will know there's no value and output an empty string.

**Review by Jeff-Stammler — CHANGES_REQUESTED** [review]

**Review by Jeff-Stammler — APPROVED** [review]
