### PR TITLE
Max Time, End of Toggles, and text_Time text fix

### LINKED ISSUE #171: when match ends, file log events to stop defense/defended (if checked) with time=max time
Must make sure we aren't logging anything beyond the 2:30 mark.  (150 seconds)

### PR DESCRIPTION
**Pull request by AdrielStammler**
Made the logger log the match length if the elapsed time is greater than it. Made the defense and defended switches do not have orphaned events if you end with them on. Fixed the bug where text_Time would sometimes not have a space in it.

Fixes #171

### CODE REVIEW

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java [hunk 1]
```diff
@@ -202,22 +202,26 @@ public void LogEvent(int in_EventId, float in_X, float in_Y, boolean in_NewSeque
...
+        String prev = "";
         String csv_line = Globals.CurrentCompetitionId + ":" + Globals.CurrentMatchNumber + ":" + Globals.CurrentDeviceId;
 
         // If this is NOT a new sequence, we need to write out the previous event id that goes with this one
         if (!in_NewSequence) prev = String.valueOf(seq_number_prev);
 
+        // If the elapsed time is greater than the match length just log the match length
+        double time = Math.round((in_time - Match.startTime) / 10.0) / 100.0;
+        time = Math.min(time, Match.TIMER_AUTO_LENGTH + Match.TIMER_TELEOP_LENGTH);
+
```
Comment (Jeff-Stammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/Logger.java:214]: why have another variable, when you can just put it all in the "String string_time" line?
like:
String string_time = String.valueof(Math.min(Math.round((in_time - Match.startTime) / 10.0) / 100.0), Match.TIMER_AUTO_LENGTH + Match.TIMER_TELEOP_LENGTH);

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java [hunk 2]
```diff
@@ -213,7 +213,7 @@ else if ((rotation_degrees >= 180) && !currentOrientation.equals(ORIENTATION_LAN
         // Map the text box variable to the actual text box
         text_Time = matchBinding.textTime;
         // Initialize the match timer textbox settings
-        text_Time.setText(getString(R.string.timer_label) + TIMER_AUTO_LENGTH);
+        text_Time.setText(getString(R.string.timer_label) + " " + TIMER_AUTO_LENGTH);
```
Comment (Jeff-Stammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:216]: The timer_label already has a space.  this isn't needed, please remove.

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java [hunk 3]
```diff
@@ -471,7 +471,7 @@ public void start_Match() {
     public void start_Teleop() {
         // Set the start Time so that the Display Time will be correct
         startTime = System.currentTimeMillis() - TIMER_AUTO_LENGTH * 1_000;
-        text_Time.setText(getString(R.string.timer_label) + TIMER_TELEOP_LENGTH / 60 + ":" + String.format("%02d", TIMER_TELEOP_LENGTH % 60));
+        text_Time.setText(getString(R.string.timer_label) + " " + TIMER_TELEOP_LENGTH / 60 + ":" + String.format("%02d", TIMER_TELEOP_LENGTH % 60));
```
Comment (Jeff-Stammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:474]: The timer_label already has a space.  please remove.

**Review by Jeff-Stammler — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java (hunk 2 above)
Comment (AdrielStammler) [reply app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:216]: Remember how you needed to have the constant “       “ because it automatically trims off all of the spaces. Well it trims off the space.

Comment (AdrielStammler) [reply app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:216]: It trimmed what I wrote I wrote seven spaces it just doesn’t look like it.

**Review by Jeff-Stammler — APPROVED** [review]
