### PR TITLE
Bug fixes

### LINKED ISSUE #167: .csv files stored
Make the number of .csv files stored on the tablet adjustable in the settings page and not a constant.

### PR DESCRIPTION
**Pull request by Jeff-Stammler**
Cleaned up Devices List to be just our CPR ones.

Added a "# of matches" to keep in the Settings, and honor it in Logger.

Cleaned up the App name and figured out how to UPDATE the app instead of reinstall. (build.gradle.kts file)

Fixes #167

### CODE REVIEW

File: app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java [hunk 1]
```diff
@@ -428,9 +465,8 @@ public void start_Match() {
     public void start_Teleop() {
         // Set the start Time so that the Display Time will be correct
         startTime = System.currentTimeMillis() - TIMER_AUTO_LENGTH * 1_000;
-        text_Time.setText(getString(R.string.timer_label) + "0:" + String.format("%02d", TIMER_AUTO_LENGTH));
+        text_Time.setText("Time: " + TIMER_TELEOP_LENGTH / 60 + ":" + String.format("%02d", TIMER_TELEOP_LENGTH % 60));
```
Comment (AdrielStammler) [inline app/src/main/java/com/cpr3663/cpr_scouting_app/Match.java:468]: Make this String not hard coded.

**Review by AdrielStammler — CHANGES_REQUESTED** [review]

**Review by AdrielStammler — APPROVED** [review]
